# Generated by Django 4.1.5 on 2023-01-12 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_number', models.CharField(max_length=10)),
                ('Department_name', models.CharField(max_length=15)),
                ('staff_work', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Personal_number', models.IntegerField()),
                ('Did_jined', models.CharField(max_length=20)),
                ('Title', models.CharField(max_length=300)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('Gender', models.CharField(max_length=15)),
                ('Salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Personalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='personal.department')),
                ('Personal', models.ManyToManyField(related_name='reservations', to='personal.personal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
